### ISSUE TITLE
Vim mode not working in firefox

### ISSUE THREAD

**Issue by guyfedwards** [codesandbox/codesandbox-client#1704]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?
Vim plugin does not load on Firefox

![2019-04-03_130637](https://user-images.githubusercontent.com/1794071/55477637-80644b00-5611-11e9-82e3-a025c76af353.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1554195707-bfa032269
| Browser | Firefox Quantum 66.0 for Fedora
| Operating System | Arch linux

**Comment by CompuIves** [comment]
Hmm, I'll take a look at this today. Interesting error, I hope that it's not this error (https://stackoverflow.com/questions/49816707/firefox-invalid-regex-group), as this would probably affect how the vim plugin works.

**Comment by guyfedwards** [comment]
That seems likely. There was a VS Code issue with the same error
https://github.com/VSCodeVim/Vim/issues/3522 which was fixed with an
update, not sure if that's something that can be applied here?

**Comment by CompuIves** [comment]
Ahh, nice find! It seems like the branch wasn't merged in the end, I'll make a comment: https://github.com/VSCodeVim/Vim/pull/3525.

**Comment by bpierre** [comment]
The branch got merged, does it means that this issue is going to be fixed in the next codesandbox-client release?

**Comment by manchicken** [comment]
This is still happening.

**Comment by bpierre** [comment]
Any update on this issue? I still get the error when trying to use the editor :-(

**Comment by bogas04** [comment]
https://github.com/codesandbox/codesandbox-client/pull/2260 removes it for FF due to lack of time. Not sure if it'll be fixed anytime soon, but sharing the status update here.

**Comment by bpierre** [comment]
@bogas04 I thought it was a VSCodeVim issue that has been fixed since? https://github.com/VSCodeVim/Vim/pull/3525

**Comment by ZKTKZ** [comment]
If you are using the Vimium extension on Firefox, you will have to add an exception to disable it on "https://codesandbox.io/*". I know this issue is closed, but I found this thread from Google, and I'm leaving this note here for others in a similar position.
