### ISSUE TITLE
Codesandbox not colour editing

### ISSUE THREAD

**Issue by didi2391** [codesandbox/codesandbox-client#2414]
![image](https://user-images.githubusercontent.com/24479458/64686083-b69dd480-d4a5-11e9-9149-547349b49124.png)

Editor is showing only black and white with code sandbox on all the browsers

Attached picture for references

Do I have to change some settings in the sandbox though to fix this issue ? Tried everything but no luck

**Comment by CompuIves** [comment]
Hey! Which sandbox do you experience this on? Also, which OS are you running?

**Comment by didi2391** [comment]
@CompuIves - Here is the sandbox url - https://codesandbox.io/s/burgerreactapp-mfbuu

OS : Windows 10

It was working fine until last week

Not sure what happened right from this week whenever I load the sandbox nothing highlights

Tried with different templates like Angular , Vue with newer sandboxes as well with different browser. Nothing works

**Comment by CompuIves** [comment]
Hmm, does this work in an incognito browser? I'm guessing there might be something wrong with loading the VSCode extensions.

**Comment by didi2391** [comment]
It doesn't work either in Incognito as well

**Comment by lbogdan** [comment]
@didi2391 Do you get any errors in the console?

**Comment by didi2391** [comment]
@lbogdan - Please see below error for console . Please let me know if you need more information on the same

![image](https://user-images.githubusercontent.com/24479458/64696355-d50eca80-d4bb-11e9-9d9f-650049637264.png)

**Comment by lbogdan** [comment]
That seems unrelated. Did you scroll up? Is that the only error?

**Comment by didi2391** [comment]
Those two are the issues that pops up in my console

Refer below for the complete screen shot

![image](https://user-images.githubusercontent.com/24479458/64696573-58302080-d4bc-11e9-85d9-bdceb5e197ec.png)

**Comment by lbogdan** [comment]
That's when loading the sandbox, I was asking more about when you load the editor - https://codesandbox.io/s/mfbuu.

**Comment by didi2391** [comment]
Find below console screen prints that I get while loading the editor

![image](https://user-images.githubusercontent.com/24479458/64754762-43986a80-d546-11e9-9250-4c2e0f4e381e.png)

I got this mirrored sandbox - https://codesandbox.io/embed/mfbuu?codemirror=1 - Highlighting works here perfectly

**Comment by didi2391** [comment]
Issue is resolved now - @CompuIves , @lbogdan , @siddharthkp

**Comment by filipelima18** [comment]
@Nikitakumawat - In our latest editor, which is powered by VS Code Web, you can directly change syntax highlighting by clicking "Plain Text" at the right of the editor's bottom bar, and then selecting the language mode you want.

**Comment by MarineCrou** [comment]
Hi ! I'm unfortunately getting the same issue @didi2391 was having. Unfortunately not sure how to go about it. Tried previous suggestions, but nothing's worked so far. Would love any insight !

**Comment by scriptcloud** [comment]
> [@Nikitakumawat](https://github.com/Nikitakumawat) - In our latest editor, which is powered by VS Code Web, you can directly change syntax highlighting by clicking "Plain Text" at the right of the editor's bottom bar, and then selecting the language mode you want.

For me only the "plain text" option was available. I strongly suspected chrome extensions to be triggering the issue, since the highlighting worked on incognito mode and on Arc browser. However the issue persisted after I disabled every single extensions, disabled cache and removed cookies. Finally I tried deleting the whole client storage, and the language options came back.

<img width="338" alt="Image" src="https://github.com/user-attachments/assets/e99ba038-b4f3-4be1-a2e4-d4b0631e6d5b" />
<img width="320" alt="Image" src="https://github.com/user-attachments/assets/0229c061-3192-4956-8ed1-f90d4b1026ee" />


I'm developing a website with sandpack-react and nextjs, with webpack hmr, there's a possibility it could have interfered with internal settings from codesandbox? i also used open in sandbox button a lot.
