### ISSUE TITLE
sandbox unable to fetch github changes

### ISSUE THREAD

**Issue by Nico-L** [codesandbox/codesandbox-client#3450]
# 🐛 bug report
Hello, I have had this problem for a few days now (about a week)
## Description of the problem
The github tab hangs up to fetching changes state. Unable to give the fetch result.

## How has this issue affected you? What are you trying to accomplish?
Unable to commit new development. I could export to a new repository but nothingtells me it won't have the same problems. And the repository is linked to a Netlify site.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/atelierlbf2020-z6e8t

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1580490943-2f3fa90ea
| Browser          | chrome & firefox
| Operating System | Windows 10 (2 different laptops)

Thanks

**Comment by lbogdan** [comment]
Hey @Nico-L ,

Can you please take a look at the devtools console and see if there's any warnings or errors? Or even better, upload a screenshot of it. Thanks!

**Comment by Nico-L** [comment]
Here it is! I should have checked :
![image](https://user-images.githubusercontent.com/11961129/73645634-f4c7aa80-4677-11ea-83f9-567e66e89605.png)
Mayube not related but I have the following errors when entering the sandbox:
![image](https://user-images.githubusercontent.com/11961129/73645753-33f5fb80-4678-11ea-8c43-1a8c669e0a9a.png)
The svgs are not from my side (I check since I used a template, I shouldn't have missed any...)

thanks

**Comment by Nico-L** [comment]
Any help ?  I'd really need to update my repository...

thanks

**Comment by Nico-L** [comment]
OK. Export to a new repository doesn't work either, so I'm left with the last solution to download the zip and try to commit elsewhere. I'm am in the process and it turns quite painful. Any hont on how to fix my issue would be most welcome.

**Comment by NawarA** [comment]
I've had to do this many times

**Comment by NawarA** [comment]
I think the reason is your code / my code is so large, the POST body being sent to github is too large for them to accept. 

Codesandbox needs a different strategy for managing diffs, then posting the entirety at once, not sure the best way to do this, but VSCode doesnt run into this issue on linux machines, because it directly executes `git` vs posting to it. Perhaps if Codesandbox had a VM / container that would automate this, it would cost a little more money, but would resolve the issue for repos that are a certain size.

I'm running into the issue as we speak. 422 and cannot export to zip, feature is not working 😞 

Must figure out a way to save changes ...

**Comment by NawarA** [comment]
Also, the cause of failure to create was zip was one of the files in Codesandbox's storage was hitting a 404, so it caused the whole thing to fail on their end. Deleting that file allowed me to create a zip. 

Still running into the 422, which is a huge hastle

**Comment by garethx** [comment]
@NawarA Please share the url to the sandbox you're having issues with. This often occurs because of a particularly large binary or log file, so it's worth checking your sandbox for that.

**Comment by NawarA** [comment]
https://codesandbox.io/s/frontend-ymgex

**Comment by NawarA** [comment]
@garethx did you take a look? I'd like to take down my code if you dont need a public link any longer

**Comment by garethx** [comment]
@NawarA I did, but your explanation looks like it's the case here - I couldn't see any unusually large file as the cause. This is an area of the product we're currently looking at revising, so I'll flag this to the team as an example.

**Comment by NawarA** [comment]
My new sandbox, which is a fork of my old one, is running into this issue again.

How do I avoid this? Its annoying to constantly have to fork my repo, try to do small changes to my react app, and hope my coding doesn't overflow your system. I'm not doing anything crazy, just working on a few components. Any way to completely avoid this? Why is it occuring in the first place?

Request
```cURL
curl "https://codesandbox.io/api/v1/sandboxes/vyv91/git/diff" ^
  -H "authority: codesandbox.io" ^
  -H "accept: application/json, text/plain, */*" ^
  -H "authorization: Bearer STRIPPED_THIS_OUT" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36" ^
  -H "sec-fetch-site: same-origin" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "referer: https://codesandbox.io/s/frontend-vyv91?file=/src/App.js" ^
  -H "accept-language: en-US,en;q=0.9" ^
  -H "cookie: visit_sandbox=1; visitor-uid=i82ef5mye2; __stripe_mid=35ba12df-d5a5-43d2-b616-b2c16452dd25; __cfduid=d729f407c4816748f42ee04b853717b741585603649; _ga_ZBMWTZ87Y9=GS1.1.1586919668.7.0.1586919668.60; _ga=GA1.2.453574545.1579891322; __vero_user=29254be7aede3b6c0d854d2a60793edeef897fb5; signedIn=true; _gid=GA1.2.854899449.1587921827; __vero_visit=true; jf9248hHFEQIU42jf298=80ceec99-e70d-4cde-b37c-09f8ab61ebec; __veroc4=^%^5B^%^5D; _gat_UA-89432508-1=1; amplitude_id_a205ed9b06a7baf5a594bdd30293aa80codesandbox.io=eyJkZXZpY2VJZCI6ImY5NTAxM2VjLTgzYTMtNDJmMC05MzIwLWMwZmVhZTgwMmQ4Y1IiLCJ1c2VySWQiOiIyOTI1NGJlN2FlZGUzYjZjMGQ4NTRkMmE2MDc5M2VkZWVmODk3ZmI1Iiwib3B0T3V0IjpmYWxzZSwic2Vzc2lvbklkIjoxNTg4MDE4ODMyNDY5LCJsYXN0RXZlbnRUaW1lIjoxNTg4MDI0ODY3MzI3LCJldmVudElkIjo5NTU0MCwiaWRlbnRpZnlJZCI6NzY1LCJzZXF1ZW5jZU51bWJlciI6OTYzMDV9" ^
  --compressed
```
Response:
```json
{"errors":{"detail":["request entity too large"]}}
```

Codesandbox Version: d68f5dac3 (latest as of 4/27/2020)

**Comment by NawarA** [comment]
Okay, to investigate further (and get around the issue of not being able to save to github...major bummer btw)... I created a whole new git repo, with 0 history, and I checked in my react app's files. 

I created a new sandbox by importing the new github repo. 

Unfortunately, the issue persists: cannot save to github because status 422 "entity too large"

These results imply the cause of the issue is the way the codesandbox application's diff is coded. It breaks when:
- Too many files in a sandbox (making the diff too large)
- Too many lines of source code (make the diff too large)
- A combination of the above

@garethx Is the function diff coded this way? I thought you mentioned there is a log somewhere...? If that's coded correctly, it shouldn't be effected by number of files / source code lines...it should only be effected by changes. Mind elaborating on the root cause? 

Thanks 💪

**Comment by garethx** [comment]
That sounds right. We're working on some improvements to the GitHub flow which incorporates optimizing commits a great deal, which should resolve this.

My mention of log file above was in reference to the fact that a lot of times when folks encounter this issue it's because of a single large file, like a log file in someone's project, rather than many files. So it's usually quickly resolved by removing that. This isn't the case here.

**Comment by NawarA** [comment]
Please let the community know when you've released a patch

🙏

**Comment by NawarA** [comment]
Hi, this issue is still open and ongoing.

To try to get around it, over the last 30 days I've tried creating several new repos, where I imported my code (with zero git history and zero large / long files). When I create a sandbox from the new historyless, small repos, I still cannot save back to Github.

I'd love to be able to save to Github. I'm sure the community feels the same way. This is important feature and breaks the DX. 

Is this issue in your current sprint? Can you please share when you will place this in your sprint? 

Its kinda a big deal to be able to save to Github 😸  ❤️

**Comment by garethx** [comment]
It is currently being worked on. We will update this issue when it's ready to go.

**Comment by NawarA** [comment]
Though it looks like the team updated the the Github interface (much better btw), I'd like to report the issue still persists.

**Comment by NawarA** [comment]
Sorry, I went to share a screenshot, but github's new UI (which I'm beta testing) is broken and not allowing me, lol

**Comment by NawarA** [comment]
@garethx quoting you:
> That sounds right. We're working on some improvements to the GitHub flow which incorporates optimizing commits a great deal, which should resolve this.

It looks like the `Github flow that incorporates optimizing commits` did not resolve the open issue.

Screenshot below:

![image](https://user-images.githubusercontent.com/2067616/85601214-0566c600-b603-11ea-8675-5ae09d26bee0.png)

### Outgoing POST is 18kb
(in case that info is helpful)
![image](https://user-images.githubusercontent.com/2067616/85601871-a48bbd80-b603-11ea-80e9-5ce76066e44f.png)


Now that you released the Github flow optimizations, can please you share:
- What's causing the bug?
- What's the patch?
- When will the patch land (date-wise)?

I suspect this is a simple fix on your backend 😆 so getting this prioritized and patched would be greatly appreciated 🙏 

Thank you dude

**Comment by NawarA** [comment]
Duplicate of #2341 #1581 #4005 #2341 

Lets consolidate the issue here. 🔧

**Comment by garethx** [comment]
Can you try it again? We've made some changes, which will hopefully have resolved this. Thanks.

**Comment by NawarA** [comment]
Success!

You rock dude!!

![image](https://user-images.githubusercontent.com/2067616/85756222-78d00c80-b6c3-11ea-814b-307647ad6ec5.png)
