### ISSUE TITLE
CodeSandbox does not load

### ISSUE THREAD

**Issue by tariqporter** [codesandbox/codesandbox-client#4381]
# 🐛 bug report

## Description of the problem

Unable to use codesandbox as patron

## How has this issue affected you? What are you trying to accomplish?

I cannot load any of my sandboxes, nor create a new sandbox. Page loads continuously with "connecting..."

![image](https://user-images.githubusercontent.com/8306435/84713398-df715f80-af38-11ea-9be3-7b3c4cc7f061.png)

This happens often and the status always says it is operational

https://status.codesandbox.io/

Have tried different internet connection, computers, and browsers

It will periodically work for a brief length of time, before not working again

**Comment by garethx** [comment]
Can you please confirm your browser and OS version along with the version of CodeSandbox (found in the footer of the editor) you're using so we can try and reproduce. It'd also be useful to know whether the problem persists in an incognito window. Thanks.

**Comment by CompuIves** [comment]
Interesting issue, could you share what your Network tab looks likes?

**Comment by vurghus-minar** [comment]
Is this similar to issue #4369?

Clearing the application storage worked for me.

![csb app 2](https://user-images.githubusercontent.com/32111718/84782948-b95fc400-aff9-11ea-9b33-f44ae89ff3cb.png)

**Comment by SaraVieira** [comment]
This seems like it is fixed with cleaning cache, seems to be a chrome issue with cache

I am closing as no other reports came in

**Comment by Igords-goncalves** [comment]
> Is this similar to issue #4369?
> 
> Clearing the application storage worked for me.
> 
> ![csb app 2](https://user-images.githubusercontent.com/32111718/84782948-b95fc400-aff9-11ea-9b33-f44ae89ff3cb.png)

Thank you, it also works for me.

**Comment by Simone4e** [comment]
Hello,

I have the same problem but clear cache doesn't help me.

Paste info from error:
Version: 0f43f56
Environment: production
Event: PITCHER:ERROR
State: CONNECTING
Branch: lwx5p3

`-1 - Error: (502) - PATH: /beta/sandboxes/branches/lwx5p3/instance - DATA: <html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8"> <title>502 Server Error</title> </head> <body text=#000000 bgcolor=#ffffff> <h1>Error: Server Error</h1> <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2> <h2></h2> <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a520410fa9f0e12","token":"7449176f14aa420c959831edd48bd5b7","version":"2023.2.0","si":100}' crossorigin="anonymous"></script> </body></html> - ERROR: SyntaxError: Unexpected token '<', " <html><hea"... is not valid JSON`

**Comment by seyedeliasfakoorian** [comment]
https://status.codesandbox.io worked and it showed uptime and downtime

**Comment by NotJack173** [comment]
Code sand box doesnt work for me i have cleared my cache and it still doesnt work

**Comment by NotJack173** [comment]
> Code sand box doesnt work for me i have cleared my cache and it still doesnt work

It says timed out...?

**Comment by Sheillah27** [comment]
Clearing my cache worked for me.

**Comment by NotJack173** [comment]
Not for me

**Comment by beqarion** [comment]
I have the same issue. It worked on my android phone, where I shared link from my pc.

**Comment by Tusharl117** [comment]
its working on my Android phone but not in my pc

**Comment by nadiamariduena** [comment]
Same issue, i cannot open it, makes my browser freeze

**Comment by FettahAud** [comment]
Same for me, it always shows this, I logged out, changed my browser and it is still the same. Even same for embedded codebox

![image](https://github.com/codesandbox/codesandbox-client/assets/74654437/8728db03-3ceb-47a0-bf88-d373972157fb)

**Comment by CompuIves** [comment]
Could it be that you're behind a corporate network? I've lately noticed that some firewalls have blocked *.csb.app. Could you also check if you can open the sandbox directly (e.g. new.csb.app)?

**Comment by FettahAud** [comment]
It's blocking it as well, where I can check that if it's blocked or not

**Comment by FettahAud** [comment]
Ohh, just found out that I have uBlockOrigin extension which is blocking them

**Comment by CompuIves** [comment]
Oh wow, `uBlockOrigin` is now blocking `*.csb.app`? That's dire. I'll check if we're on any list there!

**Comment by CompuIves** [comment]
Hmm, I can't find a list that's blocking `csb.app` altogether... Is it easy to check with the extension what rule blocks csb.app?

**Comment by mayankathem** [comment]
Image is not loading in Codesandbox
and everything is not accepting to
connect to it

**Comment by FettahAud** [comment]
> Hmm, I can't find a list that's blocking `csb.app` altogether... Is it easy to check with the extension what rule blocks csb.app?

After a couple of days it return to be blocked again, so the extension was not the reason

**Comment by erayerdin** [comment]
Yep, I'm in Turkey and this definitely seems to be an issue. 

![image](https://github.com/codesandbox/codesandbox-client/assets/2399084/71d8a8ec-6cc4-4035-8db9-5b9fb0c5f32c)

No matter what I do, I cannot connect to it for some weird reason.

**Comment by filipelima18** [comment]
@erayerdin - Unfortunately, some Turkish ISPs seem to have blocked our `csb.app` domain, which is used to serve both Devbox environments and Sandbox previews.

We recommend reporting your issue to your ISP. Hopefully, if they receive enough reports, they will lift the block. In the meantime, some users have reported that using a VPN or changing their machine's DNS servers gets around the issue.

**Comment by sKopheK** [comment]
doesn't work for me neither with clean cache (and all the other hundreds of thingies stored in my browser) nor with VPN turned off

**Comment by erayerdin** [comment]
> doesn't work for me neither with clean cache (and all the other hundreds of thingies stored in my browser) nor with VPN turned off; doesn't matter what browser i use. ![imagen](https://private-user-images.githubusercontent.com/5802917/349076338-0326e43f-ee20-4907-a666-52093d246da3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTc4NDksIm5iZiI6MTcyMTE1NzU0OSwicGF0aCI6Ii81ODAyOTE3LzM0OTA3NjMzOC0wMzI2ZTQzZi1lZTIwLTQ5MDctYTY2Ni01MjA5M2QyNDZkYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTkxOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI4YWQ4ODk2YWU2NzNlNjA3ZGYwYjNjNzQ2YWIxYzhiNzE5NzdiMTFkMzFjOTBjMmZkZDU4ZTk3Y2FlOTY5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IEWm5U6s4v7DmCO1Dp3LW35gLeodnOfduQt5dByA8mY) and file https://codesandbox.io/MwrZvD-cRfZgTv-v is linked in the HTML without actually being present on server ![imagen](https://private-user-images.githubusercontent.com/5802917/349076700-8a58b560-13e8-4a27-a30a-d686dad4e754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTc4NDksIm5iZiI6MTcyMTE1NzU0OSwicGF0aCI6Ii81ODAyOTE3LzM0OTA3NjcwMC04YTU4YjU2MC0xM2U4LTRhMjctYTMwYS1kNjg2ZGFkNGU3NTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTkxOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMwNTA1NjJjYTIzM2VmYjA0MDI0YWFjOGVkODg0MDcwYTIwOWI2ZmU1Y2QxMmVjMzc4YmRlNDIwNDcyZGEwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-FGwh7xEl-o3Ojpc2Krr-ZIPprwqdiN2DqPgFd2ts9g)

Are you located in Turkey? Did you see the other comments @sKopheK?

**Comment by sKopheK** [comment]
hi, I'm currently in Spain, tried with and without VPN on
