### ISSUE TITLE
Hot Reloading doesn't work in Next.js sandbox

### ISSUE THREAD

**Issue by cascandaliato** [codesandbox/codesandbox-client#4684]
# 🐛 bug report

## Description of the problem
Browser Preview doesn't update automatically when I change and save a file.

![image](https://user-images.githubusercontent.com/8927157/90124258-5f148280-dd60-11ea-8705-9e2c56c5790e.png)

![image](https://user-images.githubusercontent.com/8927157/90124326-7eabab00-dd60-11ea-9f05-ea903f3bb1e8.png)

## How has this issue affected you? What are you trying to accomplish?
Not having a live preview of my changes makes the feedback loop slow.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/recursing-shaw-c296s

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox | a44af0611 |
| Browser | Google Chrome Version 84.0.4147.125 (Official Build) (64-bit) |
| Operating System | Windows 10 Enterprise Version 2004 (OS Build 19041.450)

**Comment by CodeSandboxNotifications** [comment]
Hello,


This is definitely a bug we are seeing in some container sandboxes. Flagging this


Thank you
Sara Vieira 



--- original message ---
On August 13, 2020, 12:34 PM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

Browser Preview doesn't update automatically when I change and save a file.



How has this issue affected you? What are you trying to accomplish?

Not having a live preview of my changes makes the feedback loop slow.

Link to sandbox: link (optional)

https://codesandbox.io/s/recursing-shaw-c296s

Your Environment
Software Name/Version 
Сodesandbox a44af06 
Browser Google Chrome Version 84.0.4147.125 (Official Build) (64-bit) 
Operating System Windows 10 Enterprise Version 2004 (OS Build 19041.450) 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by fbryo** [comment]
I have the sam problem, even I added '''sandbox.config.json''' for activate live reload

**Comment by SaraVieira** [comment]
Hey!

We are actively working on finding out what's wrong together with Vercel

**Comment by fbryo** [comment]
Is it solved or not?

**Comment by SaraVieira** [comment]
No, we are still trying to figure out whats happening with zeit

**Comment by kstulgys** [comment]
If I download a "nextjs" project from codesandbox and run it locally it still does not have the "hot reload". Is there a way I can fix it to make it work at least locally on my machine?

**Comment by cascandaliato** [comment]
@kstulgys, I have performed the following operations and hot reload seems to work for me:
1. `Export to ZIP` the project linked above,
1. unzip it locally (in my case to Desktop),
1. run `yarn` to install packages,
1. run `yarn dev` to start the dev server
1. browse to `localhost:3000`,
1. open `pages/index.js` with any text editor, modify and save it.

I'm running Windows 10 and yarn 1.22.5

**Comment by sannek** [comment]
This should be fixed now, so I'm closing the issue. Please reopen if you're still running into issues!

**Comment by cascandaliato** [comment]
Thank you!

**Comment by rayfoss** [comment]
Seems to happen when nodemon thinks it has a good config, nothing will ever kill it. You have to manually restart the sandbox in server tools.
![Screenshot from 2021-06-02 20-02-38](https://user-images.githubusercontent.com/876076/120570351-8a468c00-c3dd-11eb-8471-71e4006606d5.png)

**Comment by AhmedCoolProjects** [comment]
![image](https://user-images.githubusercontent.com/72823374/127758275-6143b1d2-cf78-463c-8cbb-d4f1230ce400.png)
I m facing the same problem, it still not getting the new changes even after many reloading ....
Do I need to add other files or changes something in the configs ?

**Comment by rayfoss** [comment]
@AhmedCoolProjects Another issue with hot reload on codesandbox is the libraries generally do not listen on public and generally don't expose the livereload client js with CORS headers... once you get that configured it can worked... but it's not straightforward

**Comment by joshuabaker** [comment]
For those that happen across this, I resolved the issue by disabling Webpack 5 in `next.config.js`.

```js
// next.config.js

module.exports = {
  webpack5: false
}
```

**Comment by ivanschuetz** [comment]
I just had some issues with this. It mysteriously started working after reloading the original template and forking again.
