### ISSUE TITLE
Deep import problem with @angular/common/http

### ISSUE THREAD

**Issue by kylecordes** [codesandbox/codesandbox-client#623]
For some reason Code Sandbox has some difficulty with certain "deep" imports from Angular packages. See the following screenshot for an example:

![screen shot 2018-03-04 at 2 52 59 pm](https://user-images.githubusercontent.com/8799/36950516-a04a8bb4-1fbc-11e8-9544-44fe7ff0fb33.png)

Incidentally though, this import is not exactly "deep" in the traditional sense. It is not for example, pointing to a CommonJS file hidden down inside of a NPM package. Rather it is just a kind of secondary "entry point" in the `@angular/common` package. While editing the project the screen snippet came from:

https://codesandbox.io/s/github/AngularBootCamp/filtered-list-via-observable

... I also intermittently have seen brief errors rendering the running application, in which the error mentioned the same `@angular/common/http`. Still, aside from those intermittent errors, and the errant red mark on the import, the code **does run** in CodeSandbox.

Therefore, this bug report is primarily the errant red mark (the import actually works), and I suspect once that is fixed, it may also fix that intermittent other error I experienced.

**Comment by adrianfaciu** [comment]
I've experienced the same problem but in my case it does not load the module. I was trying to write a sample test for Angular and it does fail to load some of these modules.

Error message: "Could not find module in path: '@angular/core/testing'"

Sample can be viewed here: https://codesandbox.io/s/53pkll5ykp
There is a test file inside src/app/http that references that module.

Not sure if this is a bug or something not supported due to the way modules are resolved.

**Comment by lbogdan** [comment]
@adrianfaciu It's working here (well, I still get a `Cannot read property 'get' of undefined` error in `sample.interceptor.spec.ts`, but not the error you're getting). Can you give us more info about your environment (OS, browser etc.). A stack trace paste (or screenshot) would also help. Thanks!

**Comment by adrianfaciu** [comment]
Initially I saw that error with 'get of undefined' also but after I refreshed the browser once it went away and could not reproduce it anymore. Instead I ended up with the one reported above.

Env:
Windows 10 Version 1607
Chrome Version 66.0.3359.139

[Stacktrace](https://github.com/CompuIves/codesandbox-client/files/1974442/codesandbox.txt)

Later today I'll be able to check this on macOS as well and will let you know the result.

**Comment by lbogdan** [comment]
Also try doing a full site data clear (for both https://codesandbox.io/ and https://53pkll5ykp.codesandbox.io/ ) to be sure it's not a (service workers) cache issue.

**Comment by adrianfaciu** [comment]
You were right, doing a data clear removed the module error. Modules are loaded correctly even though the red underline is there. Thanks.

However the `Cannot read property 'get' of undefined` error is a bit weird since I cannot reproduce that locally, on my dev environment. When I have some time I'll investigate it a bit.

**Comment by Saeris** [comment]
This issue is over a year old, so I'm closing it for now.

If this is still a problem, could you please create a minimum reproduction example?
